version: '3'

tasks:
  test:
    cmds:
      - poetry run pytest {{.CLI_ARGS}}

  lint:
    cmds:
      - poetry run black . --check
      - poetry run mypy . --strict

  check:
    cmds:
      - task: lint
      - task: test

  fmt:
    cmds:
      - poetry run black .
